#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2019, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#

# Top level inventory.
all:

    vars:
        numstreams: 4
        ztfconnect: "public.alerts.ztf.uw.edu:9092"
        roegroupid: "{{ groups['mirrors'][0] | lower }}.ztf-mirror.roe.ac.uk"
        roeconnect: "{{ groups['kafkas'] | join(':9092,') }}:9092"
        topicdate:  "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
        topiclist: [
            "ztf_{{ topicdate }}_programid1",
            "ztf_{{ topicdate }}_programid3_public"
            ]


    # Child groups
    children:

        # Worker nodes.
        workers:
            hosts:
                work01:

        # Docker hosts.
        dockers:
            hosts:
                Ocelisean:
                Araeri:
                Nyderrad:
                Rhoawien:
                Gwirabard:
                Boasien:
                Falidon:
                Brawia:
                Glaubard:
                Legendamwen:


        # Zookeeper nodes.
        zookeepers:
            hosts:
                Ocelisean:
                Araeri:
                Nyderrad:

        # Kafka nodes.
        kafkas:
            hosts:
                Rhoawien:
                Gwirabard:
                Boasien:
                Falidon:
                Brawia:

        # MirrorMaker nodes.
        mirrors:
            hosts:
                Glaubard:
                Legendamwen:

